# Generated by Django 5.0.7 on 2024-07-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='task_section',
            new_name='workout_section',
        ),
        migrations.AddField(
            model_name='exercise',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
