# Generated by Django 5.0.7 on 2024-07-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_task_section_exercise_workout_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsection',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
